### ISSUE TITLE
Missing controls

### ISSUE THREAD

**Issue by meengit** [Trevor-/CSTK#2]
Hi @Trevor- 

* Platform: `Apple MacOS 10.13.6`
* Adobe InDesign: `CC 2017` & `CC 2019`

Thank you very much for your awesome work. Unfortunately, I was not able to make it work.

Your installation instructions are pretty simple and clear. I tried with a symlink and with copy/paste to `/Library/Application\ Support/Adobe/CEP/extensions/`. I always get a blank window.

![screen shot 2018-10-29 at 21 26 55](https://user-images.githubusercontent.com/6507355/47679370-69ce4980-dbc4-11e8-830f-be9118a7b0cd.png)

I also tried to get a `chrome://inspect/` connection to provide you a better description. However, the connection always died before I can interact.

Do you know issues like this? 

Thank you very much for your response.

**Comment by Trevor-** [comment]
Hi
I'm real busy now for the next 2+ weeks so I can't help.
But in the meantime check out these 2 post.
Let me know if you still have a problem.
http://creative-scripts.com/cstk-in-adobe-app-console-and-tool/  _The how to install section_
http://creative-scripts.com/setting-cep-debug-and-log-level/ _Shoudn't need this but see if it helps_

**Comment by meengit** [comment]
Hi,

thank you very much for your response.

No prob, I'll dig it out and send you my result.

**Comment by meengit** [comment]
Hi @Trevor-

I digged out.

## Analyzes

###  Unexpected ID behavior 

* ID Versions: CC 2017 & CC2019, latest releases
* Behavior: Empty CSTK panel, no warning, no logs, no errors

###  Other CC Applications 

For example PS CC 2019, latest release: Security warning shows up.

<img width="619" alt="screen shot" src="https://user-images.githubusercontent.com/6507355/47773786-831de580-dceb-11e8-8646-987a9655c558.png">

## Solution

### Theoretical CEP version

From `manifest.xml`:

```xml
<RequiredRuntimeList>
    <RequiredRuntime Name="CSXS" Version="6.0" />
</RequiredRuntimeList>
```

From [CEP 9.0 Cookbook, Debugging](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_9.x/Documentation/CEP%209.0%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions):

`PlayerDebugMode 1` was set for Version 6 but not for Version 9.

### Practical CEP version

Player for Version 9 must be in debug mode. On a mac:

Open a Terminal and run as `sudo`:

```bash
defaults write com.adobe.CSXS.9 PlayerDebugMode 1
killall cfprefs
```

Then restart InDesign.
